# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Spelling"

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "v3.5"

permissions:
  contents: "read"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  typos_check:
    name: "v3.5 文A Typos check"
    runs-on: "ubuntu-22.04"
    timeout-minutes: 1
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"
      - name: "Search for misspellings"
        uses: "crate-ci/typos@master"
        with:
          config: ./config/typos.toml
