name: Static Analysis
on:
  push:
    paths:
        - "src/**"
        - "tests/**"
        - "composer.json"
        - ".github/workflows/static-analysis.yaml"
jobs:
  lint-on-56:
    name: PHP 5.6 lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: make lint
  phpcs:
    name: phpcs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: make phpcs
  phpstsan:
    name: phpstan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.json') }}-${{ matrix.codeception_version }}
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.4
          version: 2.2
          args: --ignore-platform-reqs
      - run: make phpstan
