name: Test
on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - "composer.json"
      - ".github/workflows/test.yaml"
jobs:
  test_codeception_4_php_56:
    name: PHP 5.6, Codeception 4
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - name: Build WordPress image
        uses: docker/build-push-action@v4
        with:
          context: containers/php
          file: containers/php/Dockerfile-PHP-5.6
          push: false
          tags: lucatume/wp-browser-v3-wordpress:php5.6-apache
          cache-from: type=gha,scope=5.6
          cache-to: type=gha,mode=max,scope=5.6
          load: true
          build-args: |
            PHP_VERSION=5.6
            WP_IMAGE_VERSION=5
            WP_IMAGE_NAME=php-5.6apache
            WP_PHP_VERSION=5.6
            WP_DOCKERFILE=Dockerfile-PHP-5.6
            TARGET=wordpress
            USER_UID=33
            USER_GID=33
            USER_NAME=www-data
      - name: Build Codeception image
        uses: docker/build-push-action@v4
        with:
          context: containers/php
          file: containers/php/Dockerfile-PHP-5.6
          push: false
          tags: lucatume/wp-browser-v3-codecept:php5.6
          cache-from: type=gha,scope=5.6
          cache-to: type=gha,mode=max,scope=5.6
          load: true
          build-args: |
            PHP_VERSION=5.6
            WP_IMAGE_VERSION=5
            TARGET=codeception
            USER_UID=33
            USER_GID=33
            USER_NAME=www-data
      - name: Build
        run: bin/stack -p5.6 build
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: var/cache/composer
          key: ${{ runner.os }}-${{ hashFiles('**/composer.json') }}-5.6
      - name: Install dependencies
        run: bin/stack -p5.6 composer_update
      - name: Test
        run: bin/stack -p5.6 test
  test_codeception_4:
    strategy:
      matrix:
        php_version: [ '7.4', '8.0', '8.1', '8.2' ]
    name: PHP ${{ matrix.php_version }}, Codeception 4
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - name: Build WordPress image
        uses: docker/build-push-action@v4
        with:
          context: containers/php
          file: containers/php/Dockerfile
          push: false
          tags: lucatume/wp-browser-v3-wordpress:php-apache
          cache-from: type=gha,scope=${{ matrix.php_version }}
          cache-to: type=gha,mode=max,scope=${{ matrix.php_version }}
          load: true
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            WP_IMAGE_VERSION=6
            WP_IMAGE_NAME=php-apache
            WP_PHP_VERSION=${{ matrix.php_version }}
            WP_DOCKERFILE=Dockerfile
            TARGET=wordpress
            USER_UID=33
            USER_GID=33
            USER_NAME=www-data
      - name: Build Codeception image
        uses: docker/build-push-action@v4
        with:
          context: containers/php
          file: containers/php/Dockerfile
          push: false
          tags: lucatume/wp-browser-v3-codecept:php${{ matrix.php_version }}
          cache-from: type=gha,scope=${{ matrix.php_version }}
          cache-to: type=gha,mode=max,scope=${{ matrix.php_version }}
          load: true
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            WP_IMAGE_VERSION=6
            TARGET=codeception
            USER_UID=33
            USER_GID=33
            USER_NAME=www-data
      - name: Build
        run: bin/stack -p${{ matrix.php_version }} build
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: var/cache/composer
          key: ${{ runner.os }}-${{ hashFiles('**/composer.json') }}-${{ matrix.php_version }}
      - name: Install dependencies
        run: bin/stack -p${{ matrix.php_version }} composer_update
      - name: Test
        run: bin/stack -p${{ matrix.php_version }} test
